# Generated by Django 4.0.2 on 2022-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Product')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre Producto')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
    ]
