# Generated by Django 4.0.2 on 2022-02-11 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('id_product', models.IntegerField(verbose_name='ID Producto')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuacion')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('refund', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Devolucion')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
    ]
