# Generated by Django 4.0.2 on 2022-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id_search', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Busqueda')),
                ('id_product', models.IntegerField(verbose_name='ID Producto')),
            ],
            options={
                'verbose_name': 'busqueda',
                'verbose_name_plural': 'busquedas',
            },
        ),
    ]
