# Generated by Django 4.0.2 on 2022-02-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(verbose_name='Fecha de Venta'),
        ),
    ]
