# Generated by Django 4.0.2 on 2022-02-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.CharField(max_length=11, verbose_name='Fecha de Venta'),
        ),
    ]
